### ISSUE TITLE
Nuclei ROIs not exported

### ISSUE THREAD

**Issue by pwalczysko** [glencoesoftware/ome-omero-roitool#16]
If you run a *Cell detection* in QuPath, the nuclei ROIs will be drawn as well as the ROIs around the cells. The ROI OME-XML export script will ignore the ROIs around the nuclei, exporting only the ROIs around the cells. 

export and reimport the ROIs using the QuPath export and import scripts in this repo - no ROIs around cell nuclei, only cell boundaries ROIs have been recognized. (if you after the export step import into OMERO instead of back into QuPath, the experience is very similar).
![Screen Shot 2020-04-29 at 17 38 52](https://user-images.githubusercontent.com/2478303/80622169-55c90980-8a40-11ea-8f54-80996f5ced66.png)

Original ROIs as detected in QuPath
![Screen Shot 2020-04-29 at 17 41 54](https://user-images.githubusercontent.com/2478303/80622472-bc4e2780-8a40-11ea-97b6-dc2119e9d645.png)

cc @melissalinkert @jburel

**Comment by melissalinkert** [comment]
Proposed fix in #18.

**Comment by melissalinkert** [comment]
Closing now that #18 is merged.
