### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by dominikl** [glencoesoftware/ome-omero-roitool#24]
Just capturing [Queries about the ome-omero-roitool](https://forum.image.sc/t/queries-about-the-ome-omero-roitool/38566) as github issue here.

- Provide better error message if invalid server name is specified.
- Improve password handling.
- Add debug option for export command.
- Bug: Debug option for import command doesn't work.

**Comment by chris-allan** [comment]
Resolved by #26
